(ns nex.http-server-lib-test
  (:require [clojure.test :refer [deftest is testing]]
            [nex.repl :as repl]))

(deftest http-server-route-runtime
  (testing "Http_Server serves GET, POST, PUT, and DELETE routes in the JVM interpreter"
    (let [ctx (repl/init-repl-context)
          output (with-out-str
                   (repl/eval-code ctx "intern net/Http_Server")
                   (repl/eval-code ctx "let server: Http_Server := create Http_Server.make(0)")
                   (repl/eval-code ctx "server.get(\"/hello\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(\"hello\") end)")
                   (repl/eval-code ctx "server.post(\"/echo\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(req.body()) end)")
                   (repl/eval-code ctx "server.put(\"/items/:id\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(\"updated \" + req.param(\"id\") + \":\" + req.body()) end)")
                   (repl/eval-code ctx "server.delete(\"/items/:id\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(\"deleted \" + req.param(\"id\")) end)")
                   (repl/eval-code ctx "server.get(\"/hello/:name\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(\"hi \" + req.param(\"name\")) end)")
                   (repl/eval-code ctx "server.get(\"/files/*\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(req.wildcard()) end)")
                   (repl/eval-code ctx "server.get(\"/search\", fn(req: Http_Request): Http_Server_Response do result := create Http_Server_Response.text(req.query_param(\"q\")) end)")
                   (repl/eval-code ctx "server.start()")
                   (repl/eval-code ctx "print(server.is_running())")
                   (repl/eval-code ctx "print(server.port)")
                   (repl/eval-code ctx "server.port"))]
      (is (.contains output "true"))
      (let [port (Long/parseLong (last (re-seq #"\b[1-9][0-9]*\b" output)))
            client (java.net.http.HttpClient/newHttpClient)
            get-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/hello")))
                            (.GET)
                            (.build))
            route-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/hello/alice")))
                              (.GET)
                              (.build))
            wildcard-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/files/css/site.css")))
                                 (.GET)
                                 (.build))
            query-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/search?q=nex")))
                              (.GET)
                              (.build))
            post-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/echo")))
                             (.POST (java.net.http.HttpRequest$BodyPublishers/ofString "payload"))
                             (.build))
            put-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/items/42")))
                            (.method "PUT" (java.net.http.HttpRequest$BodyPublishers/ofString "body"))
                            (.build))
            delete-request (-> (java.net.http.HttpRequest/newBuilder (java.net.URI/create (str "http://127.0.0.1:" port "/items/42")))
                               (.DELETE)
                               (.build))
            get-response (.send client get-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            route-response (.send client route-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            wildcard-response (.send client wildcard-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            query-response (.send client query-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            post-response (.send client post-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            put-response (.send client put-request (java.net.http.HttpResponse$BodyHandlers/ofString))
            delete-response (.send client delete-request (java.net.http.HttpResponse$BodyHandlers/ofString))]
        (try
          (is (= 200 (.statusCode get-response)))
          (is (= "hello" (.body get-response)))
          (is (= 200 (.statusCode route-response)))
          (is (= "hi alice" (.body route-response)))
          (is (= 200 (.statusCode wildcard-response)))
          (is (= "css/site.css" (.body wildcard-response)))
          (is (= 200 (.statusCode query-response)))
          (is (= "nex" (.body query-response)))
          (is (= 200 (.statusCode post-response)))
          (is (= "payload" (.body post-response)))
          (is (= 200 (.statusCode put-response)))
          (is (= "updated 42:body" (.body put-response)))
          (is (= 200 (.statusCode delete-response)))
          (is (= "deleted 42" (.body delete-response)))
          (finally
            (repl/eval-code ctx "server.stop()")))))))
