project:
  type: book

book:
  title: "Nex Reference"
  chapters:
    - index.md
    - functions.md
    - foundational-classes.md
    - scalar-types.md
    - collection-types.md
    - cursor-types.md
    - system-classes.md
    - libraries.md
    - data.md
    - io.md
    - text.md
    - time.md
    - networking.md
    - graphics-classes.md

format:
  html:
    theme: [cosmo, ../nex-book.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
